logging:
  file:
    enable: true
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

db_meta:
  host: ${oc.env:DB_META_HOST,localhost}
  port: ${oc.env:DB_META_PORT,3307}
  user: ${oc.env:DB_META_USER}
  password: ${oc.env:DB_META_PASSWORD}
  database: ${oc.env:DB_META_DATABASE,meta}

db_dw:
  host: ${oc.env:DB_DW_HOST,localhost}
  port: ${oc.env:DB_DW_PORT,3307}
  user: ${oc.env:DB_DW_USER}
  password: ${oc.env:DB_DW_PASSWORD}
  database: ${oc.env:DB_DW_DATABASE,dw}

qdrant:
  host: ${oc.env:QDRANT_HOST,localhost}
  port: ${oc.env:QDRANT_PORT,6333}
  embedding_size: 1024

embedding:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: text-embedding-v4
  api_key: ${oc.env:EMBEDDING_API_KEY}

es:
  host: ${oc.env:ES_HOST,localhost}
  port: ${oc.env:ES_PORT,9200}
  index_name: ${oc.env:ES_INDEX_NAME,value_index}

llm:
  model_name: deepseek-v4-flash
  api_key: ${oc.env:LLM_API_KEY}
  base_url: https://api.deepseek.com
